//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO2._6
{
    using System;
    using System.Collections.Generic;
    
    public partial class inimene
    {
        public int Id { get; set; }
        public string nimi { get; set; }
        public Nullable<int> vanus { get; set; }
    }
}
